### ISSUE TITLE
Missing RCT_EXPORT_MODULE()

### ISSUE THREAD

**Issue by ee0pdt** [pjjanak/react-native-viewport#2]
Hi and thanks for creating this module. I initially received a warning when trying to run my app with the Viewport install, it said that Viewport was not exported and did I forget to use RCT_EXPORT_MODULE()? I have added it as follows in Viewport.m and all seems to work. Is this correct?

```
...

@implementation Viewport
{
  NSDictionary *_lastKnownDimensions;
}

RCT_EXPORT_MODULE()

...
```

**Comment by pjjanak** [comment]
Hey @ee0pdt - thanks for the heads up. I hadn't gotten around to updating for the 0.4.0 release. This should be fixed now and has been published to npm.
